### PR TITLE
Change getErrors() methods to return a 'map' without arguments and add test for it.

### PR DESCRIPTION
**Pull request by craftgear**
Hi, this is a change for more customize-ablity for error messages.
It's useful I can get field names and error messages pair.

So, please take a look and consider to include them into your code.

Thanks!

### CODE REVIEW

**Comment by dandean** [comment]
Hi! Thanks for the contribution and suggestion! What is the use case for getting the entire map object, instead of just getting the errors for a specific field?

**Comment by craftgear** [comment]
Hi, dandean.

Mainly for simplicity,
I want to pass errors as object at once
1. in ajax responses
   or 
2. in express, like:
   res.render('foo', {errors: req.form.getErros()});

In each case I can avoid building JSON by hand if I can call getErrors() to get an JSON.

**Comment by dandean** [comment]
I'm probably going to merge this in -- I just haven't had the time to fully think it through.

**Comment by craftgear** [comment]
Oops, I think I mistakenly made pull request.

**Pull request closed without merging**
