### PR TITLE
Various fixes/enhancements.

### PR DESCRIPTION
**Pull request by mjadobson**
**EDITED:** _14th July_

All of the filter and validation functions now reside on one object:

``` javascript
field("user.id").toInt().isInt().required()
```

There is still backwards compatability:

``` javascript
filter("user.id").toInt(),
validate("user.id").isInt().required()
```

Nested properties can now be filtered/validated with dot notation:

``` javascript
field("post.author.role").trim()
```

As well as square-bracket notation:

``` javascript
field("post[author][role]").trim()
```

Trying to filter/validate undefined properties no longer causes crashes.

``` javascript
req.body.post // is undefined
field("post.author.role")
req.form.post // is now.. { author: { role: "" } }
```

Using the `array()` flag means that field always gives an array. If the field value is an array, but there is no flag, then the first value in that array is used instead.

``` javascript
field("project.users").array(),
// undefined => [], "" => [], "q" => ["q"], ["a", "b"] => ["a", "b"]

field("project.block"),
// project.block = ["a", "b"]. No "array()", so only first value used. project.block = "A".
```

You can now filter/validate values in an array:

``` javascript
req.body.post.users = ["1","apple","3","4"]
field("post.users").array().toInt().isInt() // gives error
```

The new `passThrough` flag is set to `false` by default. When `true`, req.form has all of the properties the sources have (as before). When `false`, it only has the properties you declare.

``` javascript
// passThrough => true
req.body = { field: "hi", other: "whoa" };
field("field").toUpper()
req.form => { field: "HI", other: "whoa" };

// passThrough => false
req.body = { field: "hi", other: "whoa" };
field("field").toUpper()
req.form => { field: "HI" };
```

When `autoTrim` is set to `true`, all properties declared are automatically trimmed. Default: `false`.

``` javascript
// autoTrim => true
req.body = { field: "    whoa   ", other: ["    s  ", "  a   "] };
field("field"),
field("other")
req.form => { field: "whoa", other: ["s", "a"] };
```

When using multiple sources, the sources are now deep merged, so:

``` javascript
req.body = { a: { b: { c: "www" } } };
req.other = { a: { b: { x: "99probs" } } };
field("a.b.c"),
field("a.b.x")
req.form => { a: { b: { c: "www", x: "99probs" } } };
```

The `custom()` function now supports both filtering and validation, depending on whether it returns a value, returns undefined, or throw an error. Explicit usage exists with `customFilter()` and `customValidator()`

`req.form.getErrors()` now gives the full map of errors. (From: https://github.com/dandean/express-form/pull/3)

I've also rewritten various chunks of it to make it easier to read (for me at least). This passes all of the old unit tests, and I've created a few new tests for some of the added functionality.

**TODO:**
- Filter/validation functions for arrays themselves. (.push(), .arrayLength(), etc.)
- Add some tests for deep merging.
- Maybe use `Object.create(obj).__proto__;` isntead of `JSON.parse(JSON.stringify(obj));` for cloning objects.
- Update docs
- Getting errors on arrays looks a bit weird:

``` javascript
 req.body = { users: ["1","asd","ds","gds","9"] }
 field("users").array().toInt().isInt()
 req.form.getErrors("users") => ["users is not an integer", "users is not an integer", "users is not an integer"];
 // I have no idea what this should look like, tbh.
```

### CODE REVIEW

**Comment by mjadobson** [comment]
This has some bugs regarding numerical values and incomplete support for arrays. Will try and fix that up.

**Comment by dandean** [comment]
Thanks for letting me know. I've been super busy with other work, so haven't had the time to merge it. Some unit test for the new functionality would be super helpful, and would make it much safer for me to merge in the new work.

**Comment by mjadobson** [comment]
No worries.

One thing I am considering doing is changing the api a bit. This consolidates the filter and validate functions to keep it dry. And I can't think of a decent use case, but it gives you flexibility to order validation and filtering in any way you like.

``` javascript
form(
    field("blog.post.title").toUpper().required(),
    field("blog.post.author").toInt().isInt().required()
)
```

Also, an array property to force that field to be an array, as well as filter & validation functions to do with arrays:

``` javascript
form(
    field("project.users").array(),
    // undefined => [], "" => [], "q" => ["q"], ["a", "b"] => ["a", "b"]

    field("project.block").toUpper(),
    // project.block = ["a", "b"]. No "array()", so only first value used. project.block = "A".

    field("project.tasks").array().push("Foo?").arrayLength(1, 4).length(1,5)
    // project.tasks = ["a","qwertyu"]. "Foo?" pushed. arrayLength ok. "qwertyu" fails charlength.
)
```

What do you think?

**Comment by mjadobson** [comment]
Pushed a massive update. Should be safe to pull, but obv test it out first.

**Comment by dandean** [comment]
Holy shit! This is quite the rewrite!

At first glance, I really like the changes. Merging `filter` and `validator` into the unified `field` API is much cleaner.

**Comment by dandean** [comment]
Also, I love how you're dealing with arrays -- very nice.

**Comment by wavded** [comment]
good work @Sugarstack, my only question is can 'passThrough' be true by default.  before the rewrite, this was the case, req.form would be populated with all the form elements.  I think this is desired because you get a cleaned up set of your form and don't have to cherry pick between that and req.body or req.param .. etc... thoughts?

**Comment by mjadobson** [comment]
I did think about that, but I thought that it was safer for `passThrough` to be false by default. I think taking data for granted from `req.body` is generally a bad idea.

**For example:**

You try and access `req.form.post.author`, but `req.body.post` is `undefined`, causing node to crash.
Or, you try and use a `String` method on `req.body.foo`, but it's actually an array, causing node to crash.

Simply declaring those fields with `field("post.author")` & `field("foo")` will make sure that won't happen.

**Pull request merged**
