### PR TITLE
(plz ignore, wrong commit) corrected res.local -> res.locals

### PR DESCRIPTION
**Pull request by guersam**

### CODE REVIEW

**Comment by dandean** [comment]
Will this break compatibility with express 2.x ? If so it would be best to update with backwards compatibility in mind.

**Comment by mwawrusch** [comment]
I just checked this back with masters and the express 2.0 code base and I think this patch might not be correct. I will investigate a bit Friday.

**Comment by guersam** [comment]
Sorry for wrong patch, I just checked 2.0. 
In my 3.0 pre-alpha app, that line was executed sometimes and occurred error. It might be caused by another middleware.
I'll check it with 3.0alpha again.

**Comment by guersam** [comment]
No issue on 3.0alpha. Sorry again.

**Comment by dandean** [comment]
No problem. Thanks for checking.

**Pull request closed without merging**
